services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports: ["8000:8000"]
  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports: ["8501:8501"]
    depends_on: [api]
